### ISSUE TITLE
Add Lake Erie 5-minute grid shapefile and basemap

### ISSUE THREAD

**Issue by mrdufour** [LakeErie-PreyFish-Acoustics/eriespatial#4]
Essential for selecting sampling locations in LE hydroacoustic survey

**Comment by zjslagle** [comment]
Unsure what the next step is (damn my poor note taking!). I believe I merged this with the development branch, but not sure if "development" needs to be merged with main now?

**Comment by HoldenJe** [comment]
3d497b8298db94ef3268b7f51dae272a8b3525a6 adds rda files to complete package build.

I'll add my example to the README then do a version increment before merging to main.

**Comment by mrdufour** [comment]
@zjslagle @HoldenJe Sweet! We are slowly but surely adjusting to this workflow!

**Comment by mrdufour** [comment]
Closing issue #4
