### ISSUE TITLE
5min grid missing crs

### ISSUE THREAD

**Issue by HoldenJe** [LakeErie-PreyFish-Acoustics/eriespatial#6]
@zjslagle I was attempting to update the README with an example for the 5 min grid and couldn't get it to plot using the ggplot method. I needed to add the crs to the feature before it would overlay on the map. Should we add the crs to the `import_layers.R` file? At line 94? Not sure why the other shapefiles didn't require it but the grid does.

See example:
``` r
library(eriespatial)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(ggplot2)
data("shape_5mingrid")
data("shape_erieshore")

base_erieshore + geom_sf(data = shape_ebstrata, alpha = 0.1)
```

![](https://i.imgur.com/BDKwMeo.png)

``` r
base_erieshore + geom_sf(data = shape_5mingrid, alpha = 0.1)
#> Error in st_transform.sfc(X[[i]], ...): cannot transform sfc object with missing crs

st_crs(shape_5mingrid) <- 4269
base_erieshore + geom_sf(data = shape_5mingrid, alpha = 0.1)
```

![](https://i.imgur.com/1GjNDnv.png)

<sup>Created on 2022-09-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by zjslagle** [comment]
This may be related to my comment on issue #5; the shape_5mingrid was missing a projection, so I believe I added a projection, saved a new shapefile, pushed, and merged with the Development branch. Do we need to merge Development with main? Or what is the intended workflow from there?

**Comment by HoldenJe** [comment]
Your fix worked. After the new shapefile was loaded `import_layers.R` needed to be run to rebuild the rda files that get called. After I sourced the the script the example above worked. I'll push the new rda files and close the two issues.

``` r
library(eriespatial)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(ggplot2)
data("shape_5mingrid")
data("shape_erieshore")

base_erieshore + geom_sf(data = shape_5mingrid, alpha = 0.1)
```

![](https://i.imgur.com/dEabYFj.png)

<sup>Created on 2022-09-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
